const races=[
 {id:'niigata12',venue:'新潟',r:12,time:'18:05',status:'BUY',score:84,axis:'高',rough:'中',tickets:10,role:'A',summary:'軸候補は強いが、軸飛びを3点で保険。10点で主要シナリオを覆える。',horses:[['◎','8 サトノエスケープ',88,'同舞台で再現性が高く、複数展開でも残りやすい'],['○','3 スリーコーズ',85,'先行力があり新潟1200mへの適合が高い'],['▲','1 ガルディーノ',82,'前受けできる能力上位。先行競合だけ注意'],['☆','6 ジャックナダル',78,'能力上限は高いが条件変化に不確実性'],['△','14 ラベンダーヘイズ',74,'ダート戻りの条件変化要員'],['△','4 エテオクロス',71,'差し込みの3着侵入候補']],formation:'1列目：8 / 2列目：1・3 / 3列目：1・3・4・6・14',exclude:'本線7点＋軸飛び3点を採用。IPAT順の除外表示は実データ接続後に自動生成。',failure:'8が位置を取れず、1・3・6・14内で完結する形。'},
 {id:'chukyo12',venue:'中京',r:12,time:'18:15',status:'BUY',score:81,axis:'中高',rough:'中',tickets:10,role:'A',summary:'能力上位2頭が強いが1頭固定は避ける。10点で軸飛びを含めて対応。',horses:[['◎','12 ラヴネヴァーダイズ',87,'1200mでの再現性が高い'],['○','11 ヒルノプーリア',86,'能力上位だが距離短縮の不確実性あり'],['▲','1 ヴォンドゥ',80,'軽量と同条件実績を評価'],['☆','3 アーガイルショア',77,'前走内容から相手候補'],['△','8 レジェンダリーデイ',73,'前残り担当'],['△','10 グラスゴー',69,'3着侵入候補']],formation:'1列目：11・12 / 2列目：1・3・8・11・12 / 3列目：1・3・8・10・11・12',exclude:'上から5・9・10・11・13・14番目を削除 → 最終10点',failure:'12だけを固定すると取り逃すため、11側からの完結も残す。'},
 {id:'sample',venue:'札幌',r:10,time:'15:00',status:'PASS',score:58,axis:'低',rough:'高',tickets:0,role:'PASS',summary:'候補を12点以内に圧縮すると主要シナリオを落とすため見送り。',horses:[['◎','3 サンプルホースA',72,'能力上位だが展開依存が大きい'],['○','7 サンプルホースB',70,'構造適合は高いが安定性不足'],['▲','11 サンプルホースC',68,'穴候補だが不確実性大']],formation:'購入適格判定でPASS',exclude:'12点以内で主要敗因シナリオを覆えないため買い目生成を停止。',failure:'軸不明瞭・展開分岐が大きく、買い目水増しにつながる。'}
];
const list=document.getElementById('raceList'),detail=document.getElementById('detail'),content=document.getElementById('detailContent'),back=document.getElementById('backBtn');
function renderList(){detail.classList.add('hidden');list.classList.remove('hidden');list.innerHTML=races.map(x=>`<article class="race-card" data-id="${x.id}"><div class="race-top"><div class="race-name">${x.venue} ${x.r}R <small>${x.time}</small></div><span class="status ${x.status}">${x.status}</span></div><div class="score">${x.score}<small>/100</small></div><div>${x.summary}</div><div class="metrics"><div class="metric"><span>軸耐久性</span><strong>${x.axis}</strong></div><div class="metric"><span>荒れ度</span><strong>${x.rough}</strong></div><div class="metric"><span>推奨点数</span><strong>${x.tickets||'—'}</strong></div></div></article>`).join('');document.querySelectorAll('.race-card').forEach(el=>el.onclick=()=>showDetail(el.dataset.id));}
function showDetail(id){const x=races.find(r=>r.id===id);list.classList.add('hidden');detail.classList.remove('hidden');content.innerHTML=`<section class="detail-card"><div class="detail-hero"><div><div class="kicker">AI CONCLUSION</div><h2>${x.venue} ${x.r}R</h2><p>${x.summary}</p><div class="pill-row"><span class="status ${x.status}">${x.status}</span><span class="pill">A/B/C: ${x.role}</span><span class="pill">軸耐久性 ${x.axis}</span><span class="pill">推奨 ${x.tickets||0}点</span></div></div><div class="score">${x.score}<small>/100</small></div></div></section><section class="detail-card"><h3>AIの馬評価</h3><div class="horse-list">${x.horses.map(h=>`<div class="horse"><div class="mark">${h[0]}</div><div><div class="horse-name">${h[1]}</div><div class="horse-reason">${h[3]}</div></div><div class="horse-score">${h[2]}</div></div>`).join('')}</div></section><section class="detail-card"><h3>買い目</h3><div class="formation">${x.formation}</div><div class="exclude">${x.exclude}</div></section><section class="detail-card"><h3>AIが警戒している負け方</h3><p>${x.failure}</p><div class="expert-only"><hr><h4>Expert表示</h4><p>能力順位と市場評価は分離。予想封印後にのみオッズを読み、T-4分でEV判定する。候補追加は市場情報では行わない。</p></div></section>`;window.scrollTo({top:0,behavior:'smooth'});}
back.onclick=renderList;
document.querySelectorAll('.mode-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.mode-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.body.classList.toggle('expert',btn.dataset.mode==='expert');});
renderList();
